/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.primeiraavaliacao;

/**
 *
 * @author biaoz
 */
public class SimuladorFinanceiro extends javax.swing.JFrame {

    /**
     * Creates new form SimuladorFinanceiro
     */
    public SimuladorFinanceiro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPergunta1 = new javax.swing.JLabel();
        lblPergunta2 = new javax.swing.JLabel();
        txtValorSalario = new javax.swing.JTextField();
        txtCarga = new javax.swing.JTextField();
        lblPergunta3 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        lblGasto = new javax.swing.JLabel();
        lblFlow = new javax.swing.JLabel();
        lblPlano = new javax.swing.JLabel();
        lblEconomia = new javax.swing.JLabel();
        btnBotao = new javax.swing.JButton();
        lblPergunta4 = new javax.swing.JLabel();
        txtTempo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 102, 51));
        lblTitulo.setText("FLOW");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel2.setText("simulador financeiro");

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Utilize o nosso simulador para ver os resultados que nosso sistema trás para você!");

        lblPergunta1.setText("Quanto cada funcionário recebe por mês?");

        lblPergunta2.setText("Qual a carga horária de cada funcionário?");

        lblPergunta3.setText("Qual o total de funcionários?");

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        btnBotao.setBackground(new java.awt.Color(0, 102, 51));
        btnBotao.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnBotao.setText("SIMULAR");
        btnBotao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBotaoActionPerformed(evt);
            }
        });

        lblPergunta4.setText("Quanto tempo seu estabelecimento fica aberto?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(189, 189, 189)
                                .addComponent(lblTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPergunta4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTempo))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lblPergunta2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblPergunta3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblPergunta1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtValorSalario))))
                                .addGap(35, 35, 35)
                                .addComponent(btnBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblEconomia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblPlano, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblGasto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFlow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2)))
                .addGap(5, 5, 5)
                .addComponent(jLabel3)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPergunta1)
                    .addComponent(txtValorSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPergunta3)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPergunta2)
                            .addComponent(txtCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPergunta4)
                    .addComponent(txtTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(lblPlano, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFlow, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lblEconomia, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBotaoActionPerformed
        // TODO add your handling code here:
        
        // Extraindo os valores das caixas de texto
        String salariotxt=txtValorSalario.getText(), cargatxt=txtCarga.getText(), 
                totaltxt=txtTotal.getText(), tempotxt=txtTempo.getText();
        String porcentagemE = "30%", porcentagemP = "20%", porcentagemL = "10%";
        
        // Tranformando todos em doubles (valores, não são inteiros)
        Integer salario=Integer.valueOf(salariotxt), carga=Integer.valueOf(cargatxt), 
                total=Integer.valueOf(totaltxt), tempo=Integer.valueOf(tempotxt);
        
        // Craindo contas
        Integer contaGastoAtual = salario*total, 
                contaGastoAno = contaGastoAtual*12,
                contaEconomiaFlow,
                contaEconomiaFlowAno,
                contaValorEconomia,
                contaValorEconomiaAno;
               
        //Mostrando resultado
             if(total >= 100 || tempo >= 16) {
                 
            contaEconomiaFlow = contaGastoAtual - ((contaGastoAtual/10)*3); 
            contaValorEconomia= contaGastoAtual - contaEconomiaFlow;
            contaValorEconomiaAno = contaValorEconomia*12;
            contaEconomiaFlowAno = contaEconomiaFlow * 12;
            lblPlano.setText("Pelo tamanho do seu negócio, a melhor escolha é o plano Expert");
             lblFlow.setText(String.format("Com a Flow, você terá uma economia a partir de %s, "
                    + "tendo um gasto mensal de R$%d e anual de R$%d.",porcentagemE,
                    contaEconomiaFlow, contaEconomiaFlowAno));
            lblEconomia.setText(String.format("Você economiza até R$%d por mês e R$%d por ano!", 
                    contaValorEconomia, contaValorEconomiaAno));
            
        } else if (total<100  && total>16 || tempo > 10 && tempo < 16) {
             contaEconomiaFlow = contaGastoAtual - ((contaGastoAtual/10)*2); 
            contaValorEconomia= contaGastoAtual - contaEconomiaFlow;
            contaValorEconomiaAno = contaValorEconomia*12;
            contaEconomiaFlowAno = contaEconomiaFlow * 12;
            lblPlano.setText("Pelo tamanho do seu negócio, a melhor escolha é o plano Plus");
            lblFlow.setText(String.format("Com a Flow, você terá uma economia a partir de %s,"
                    + "tendo um gasto mensal de R$%d e anual de R$%d.",porcentagemP,
                    contaEconomiaFlow, contaEconomiaFlowAno));
            lblEconomia.setText(String.format("Você economiza até R$%d por mês e R$%d por ano!", 
                    contaValorEconomia, contaValorEconomiaAno));
        } else {
             contaEconomiaFlow = contaGastoAtual - ((contaGastoAtual/10)*1); 
            contaValorEconomia= contaGastoAtual - contaEconomiaFlow;
            contaValorEconomiaAno = contaValorEconomia*12;
            contaEconomiaFlowAno = contaEconomiaFlow * 12;
            lblPlano.setText("Pelo tamanho do seu negócio, a melhor escolha é o plano Light");
            lblFlow.setText(String.format("Com a Flow, você terá uma economia a partir de %s,"
                    +"tendo um gasto mensal de R$%d e anual de R$%d.",porcentagemL,
                    contaEconomiaFlow, contaEconomiaFlowAno));
            lblEconomia.setText(String.format("Você economiza até R$%d por mês e R$%d por ano!", 
                    contaValorEconomia, contaValorEconomiaAno));
            
        }
             
            lblGasto.setText(String.format("O seu gasto hoje é de R$%d mensal,"
                    + " R$%d anual.", contaGastoAtual, contaGastoAno));     
    }//GEN-LAST:event_btnBotaoActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimuladorFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimuladorFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimuladorFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimuladorFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimuladorFinanceiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBotao;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblEconomia;
    private javax.swing.JLabel lblFlow;
    private javax.swing.JLabel lblGasto;
    private javax.swing.JLabel lblPergunta1;
    private javax.swing.JLabel lblPergunta2;
    private javax.swing.JLabel lblPergunta3;
    private javax.swing.JLabel lblPergunta4;
    private javax.swing.JLabel lblPlano;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCarga;
    private javax.swing.JTextField txtTempo;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtValorSalario;
    // End of variables declaration//GEN-END:variables
}
